# -*- coding: utf-8 -*-
"""AC3-PET-STORE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CIYs3PA3u5KEoWdK-9zy95gY8CWUfpIV
"""

pip -q install google-colab-selenium selenium

import google_colab_selenium as gs
print("Bibliotecas instaladas com sucesso.")

from urllib.parse import quote

# Define o HTML da página de cadastro
HTML_DEMO = """
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <title>Demo QA - Formulário</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background: #f4f6f8;
      padding: 30px;
    }
    .card {
      max-width: 520px;
      margin: 0 auto;
      background: white;
      padding: 24px;
      border-radius: 12px;
      box-shadow: 0 2px 12px rgba(0,0,0,0.08);
    }
    h1 {
      margin-top: 0;
      font-size: 24px;
    }
    p {
      color: #444;
    }
    label {
      display: block;
      margin-top: 14px;
      font-weight: bold;
    }
    input {
      width: 100%;
      padding: 10px;
      margin-top: 6px;
      border: 1px solid #cfd8dc;
      border-radius: 8px;
      box-sizing: border-box;
    }
    button {
      margin-top: 18px;
      width: 100%;
      padding: 12px;
      border: none;
      border-radius: 8px;
      cursor: pointer;
      font-size: 16px;
      background: #1565c0;
      color: white;
    }
    #resultMsg {
      margin-top: 18px;
      padding: 12px;
      border-radius: 8px;
      display: none;
      font-weight: bold;
    }
    .success {
      display: block !important;
      background: #e8f5e9;
      color: #1b5e20;
    }
    .error {
      display: block !important;
      background: #ffebee;
      color: #b71c1c;
    }
  </style>
</head>
<body>
  <div class="card">
    <h1>Cadastro de Produtos</h1>
    <p>Preencha os dados abaixo para cadastrar um novo produto.</p>

    <label for="nome">Nome</label>
    <input id="nome" type="text" placeholder="Digite seu nome">

    <label for="id">Id</label>
    <input id="id" type="text" placeholder="Digite o identificador do produto">

    <label for="valor">Valor</label>
    <input id="valor" type="number" placeholder="Digite o valor de venda">

    <label for="estoque">Estoque</label>
    <input id="estoque" type="number" placeholder="Digite o estoque atual">

    <button id="submitBtn" onclick="validarFormulario()">Enviar</button>

    <div id="resultMsg"></div>
  </div>

  <script>
    const idsCadastrados = [];

    // Lógica para validar os campos e exibir mensagens
    function validarFormulario() {
      const nome = document.getElementById('nome').value.trim();
      const id = document.getElementById('id').value.trim();
      const valor = document.getElementById('valor').value.trim();
      const estoque = document.getElementById('estoque').value.trim();
      const msg = document.getElementById('resultMsg');

      msg.className = '';
      msg.style.display = 'none';

      // Validação de campos vazios
      if (!nome || !id || !valor || !estoque) {
        msg.textContent = 'Erro: todos os campos são obrigatórios.';
        msg.classList.add('error');
        return;
      }

      // Verifica se o ID já existe no sistema
      if (idsCadastrados.includes(id)) {
        msg.textContent = `Erro: o ID "${id}" já está cadastrado.`;
        msg.classList.add('error');
        return;
      }

      // Regras de negócio básicas
      if (Number(valor) <= 0) {
        msg.textContent = 'Erro: o valor deve ser maior que zero.';
        msg.classList.add('error');
        return;
      }

      if (Number(estoque) < 0) {
        msg.textContent = 'Erro: o estoque não pode ser negativo.';
        msg.classList.add('error');
        return;
      }

      idsCadastrados.push(id);

      // Exibe sucesso formatando os valores
      msg.textContent = `Sucesso: registro criado para ${nome} (ID: ${id}) no valor de R$ ${Number(valor).toFixed(2)} com o estoque de ${parseInt(estoque)}.`;
      msg.classList.add('success');
    }
  </script>
</body>
</html>
"""

# Gera a URL para o Selenium acessar
DEMO_URL = "data:text/html;charset=utf-8," + quote(HTML_DEMO)
print("Página HTML preparada com sucesso.")

from urllib.parse import quote

# Define o HTML da página de cadastro
HTML_DEMO = """
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <title>Demo QA - Formulário</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background: #f4f6f8;
      padding: 30px;
      margin: 0;
    }

    .layout {
      display: flex;
      gap: 24px;
      align-items: flex-start;
    }

    /* Coluna esquerda: formulário */
    .card {
      flex: 0 0 360px;
      background: white;
      padding: 24px;
      border-radius: 12px;
      box-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);
    }

    h1 {
      margin-top: 0;
      font-size: 24px;
    }

    p {
      color: #444;
    }

    label {
      display: block;
      margin-top: 14px;
      font-weight: bold;
    }

    input {
      width: 100%;
      padding: 10px;
      margin-top: 6px;
      border: 1px solid #cfd8dc;
      border-radius: 8px;
      box-sizing: border-box;
    }

    input:disabled {
      background: #f0f0f0;
      color: #888;
      cursor: not-allowed;
    }

    button {
      margin-top: 18px;
      width: 100%;
      padding: 12px;
      border: none;
      border-radius: 8px;
      cursor: pointer;
      font-size: 16px;
      background: #1565c0;
      color: white;
    }

    button:hover {
      background: #0d47a1;
    }

    #btnCancelar {
      background: #757575;
      margin-top: 8px;
    }

    #btnCancelar:hover {
      background: #616161;
    }

    #resultMsg {
      margin-top: 18px;
      padding: 12px;
      border-radius: 8px;
      display: none;
      font-weight: bold;
    }

    .success {
      display: block !important;
      background: #e8f5e9;
      color: #1b5e20;
    }

    .error {
      display: block !important;
      background: #ffebee;
      color: #b71c1c;
    }

    /* Coluna direita: lista de produtos */
    .product-list {
      flex: 1;
      background: white;
      padding: 24px;
      border-radius: 12px;
      box-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);
      min-height: 200px;
    }

    .product-list h2 {
      margin-top: 0;
      font-size: 20px;
      color: #1565c0;
      border-bottom: 2px solid #e3f2fd;
      padding-bottom: 10px;
    }

    #lista-vazia {
      color: #90a4ae;
      font-style: italic;
    }

    #campoPesquisa {
      width: 100%;
      padding: 8px 12px;
      margin-bottom: 14px;
      border: 1px solid #cfd8dc;
      border-radius: 8px;
      box-sizing: border-box;
      font-size: 14px;
    }

    .produto-item {
      border: 1px solid #e0e0e0;
      border-radius: 8px;
      margin-bottom: 10px;
      overflow: hidden;
      transition: box-shadow 0.2s;
    }

    .produto-item:hover {
      box-shadow: 0 2px 8px rgba(21, 101, 192, 0.15);
    }

    .produto-header {
      display: flex;
      align-items: center;
      padding: 12px 16px;
      background: #f5f5f5;
      gap: 12px;
    }

    .produto-header-click {
      display: flex;
      align-items: center;
      gap: 12px;
      flex: 1;
      cursor: pointer;
      user-select: none;
    }

    .produto-header-click:hover .produto-nome-header {
      color: #1565c0;
    }

    .badge-id {
      background: #1565c0;
      color: white;
      border-radius: 6px;
      padding: 2px 10px;
      font-size: 13px;
      font-weight: bold;
      white-space: nowrap;
    }

    .produto-nome-header {
      flex: 1;
      font-weight: bold;
      font-size: 15px;
    }

    .chevron {
      font-size: 12px;
      color: #90a4ae;
      transition: transform 0.25s;
    }

    .btn-editar {
      margin-top: 0;
      width: auto;
      padding: 4px 12px;
      font-size: 13px;
      background: #ff8f00;
      color: white;
      border: none;
      border-radius: 6px;
      cursor: pointer;
      white-space: nowrap;
    }

    .btn-editar:hover {
      background: #e65100;
    }

    .btn-excluir {
      margin-top: 0;
      width: auto;
      padding: 4px 12px;
      font-size: 13px;
      background: #c62828;
      color: white;
      border: none;
      border-radius: 6px;
      cursor: pointer;
      white-space: nowrap;
    }

    .btn-excluir:hover {
      background: #b71c1c;
    }

    .produto-details {
      display: none;
      padding: 14px 16px;
      background: white;
      border-top: 1px solid #e0e0e0;
    }

    .produto-details table {
      width: 100%;
      border-collapse: collapse;
    }

    .produto-details td {
      padding: 6px 0;
      font-size: 14px;
    }

    .produto-details td:first-child {
      color: #607d8b;
      width: 90px;
      font-weight: bold;
    }

    .produto-item.open .chevron {
      transform: rotate(180deg);
    }

    .produto-item.open .produto-details {
      display: block;
    }
  </style>
</head>

<body>

  <div class="layout">

    <!-- Coluna esquerda: formulário -->
    <div class="card">
      <h1 id="formTitulo">Cadastro de Produtos</h1>
      <p id="formDescricao">Preencha os dados abaixo para cadastrar um novo produto.</p>

      <label for="nome">Nome</label>
      <input id="nome" type="text" placeholder="Digite o nome do produto">

      <label for="id">Id</label>
      <input id="id" type="text" placeholder="Digite o identificador do produto">

      <label for="valor">Valor</label>
      <input id="valor" type="number" placeholder="Digite o valor de venda">

      <label for="estoque">Estoque</label>
      <input id="estoque" type="number" placeholder="Digite o estoque atual">

      <button id="submitBtn" onclick="acaoFormulario()">Enviar</button>
      <button id="btnCancelar" onclick="cancelarEdicao()" style="display:none;">Cancelar</button>

      <div id="resultMsg"></div>
    </div>

    <!-- Coluna direita: lista de produtos -->
    <div class="product-list">
      <h2>Produtos Cadastrados</h2>
      <input id="campoPesquisa" type="text" placeholder="Pesquisar por nome ou ID..." oninput="pesquisar()">
      <p id="lista-vazia">Nenhum produto cadastrado ainda.</p>
      <div id="produtos-container"></div>
    </div>

  </div>

  <script>
    const idsCadastrados = [];
    const produtos = [];
    let modoEdicao = false;
    let idEmEdicao = null;

    // ── Decide entre cadastrar ou salvar edição ──
    function acaoFormulario() {
      if (modoEdicao) {
        salvarEdicao();
      } else {
        validarFormulario();
      }
    }

    // ── Cadastro ──
    function validarFormulario() {
      const nome = document.getElementById('nome').value.trim();
      const id = document.getElementById('id').value.trim();
      const valor = document.getElementById('valor').value.trim();
      const estoque = document.getElementById('estoque').value.trim();
      const msg = document.getElementById('resultMsg');

      msg.className = '';
      msg.style.display = 'none';

      if (!nome || !id || !valor || !estoque) {
        msg.textContent = 'Erro: todos os campos são obrigatórios.';
        msg.classList.add('error');
        return;
      }

      if (idsCadastrados.includes(id)) {
        msg.textContent = `Erro: o ID "${id}" já está cadastrado.`;
        msg.classList.add('error');
        return;
      }

      if (Number(valor) <= 0) {
        msg.textContent = 'Erro: o valor deve ser maior que zero.';
        msg.classList.add('error');
        return;
      }

      if (Number(estoque) < 0) {
        msg.textContent = 'Erro: o estoque não pode ser negativo.';
        msg.classList.add('error');
        return;
      }

      idsCadastrados.push(id);
      const p = { id, nome, valor: Number(valor), estoque: parseInt(estoque) };
      produtos.push(p);

      msg.textContent = `Sucesso: registro criado para ${nome} (ID: ${id}) no valor de R$ ${p.valor.toFixed(2)} com o estoque de ${p.estoque}.`;
      msg.classList.add('success');

      adicionarProdutoNaLista(p);

      document.getElementById('nome').value = '';
      document.getElementById('id').value = '';
      document.getElementById('valor').value = '';
      document.getElementById('estoque').value = '';
    }

    // ── Ativa modo edição ──
    function editarProduto(id) {
      const produto = produtos.find(p => p.id === id);
      if (!produto) return;

      modoEdicao = true;
      idEmEdicao = id;

      document.getElementById('formTitulo').textContent = 'Editar Produto';
      document.getElementById('formDescricao').textContent = 'Altere os campos desejados e clique em Salvar.';

      document.getElementById('nome').value = produto.nome;
      document.getElementById('id').value = produto.id;
      document.getElementById('id').disabled = true;
      document.getElementById('valor').value = produto.valor;
      document.getElementById('estoque').value = produto.estoque;

      document.getElementById('submitBtn').textContent = 'Salvar';
      document.getElementById('btnCancelar').style.display = 'block';

      const msg = document.getElementById('resultMsg');
      msg.className = '';
      msg.style.display = 'none';
    }

    // ── Salva a edição após confirmação ──
    function salvarEdicao() {
      const nome = document.getElementById('nome').value.trim();
      const valor = document.getElementById('valor').value.trim();
      const estoque = document.getElementById('estoque').value.trim();
      const msg = document.getElementById('resultMsg');

      msg.className = '';
      msg.style.display = 'none';

      if (!nome || !valor || !estoque) {
        msg.textContent = 'Erro: todos os campos são obrigatórios.';
        msg.classList.add('error');
        return;
      }

      if (Number(valor) <= 0) {
        msg.textContent = 'Erro: o valor deve ser maior que zero.';
        msg.classList.add('error');
        return;
      }

      if (Number(estoque) < 0) {
        msg.textContent = 'Erro: o estoque não pode ser negativo.';
        msg.classList.add('error');
        return;
      }

      const confirmar = confirm(`Deseja realmente salvar as alterações do produto "${nome}" (ID: ${idEmEdicao})?`);
      if (!confirmar) return;

      // Atualiza o objeto no array
      const produto = produtos.find(p => p.id === idEmEdicao);
      produto.nome = nome;
      produto.valor = Number(valor);
      produto.estoque = parseInt(estoque);

      // Atualiza o card na lista da direita
      atualizarCardNaLista(produto);

      msg.textContent = `Produto "${nome}" (ID: ${idEmEdicao}) atualizado com sucesso.`;
      msg.classList.add('success');

      cancelarEdicao();
    }

    // ── Cancela e volta ao modo cadastro ──
    function cancelarEdicao() {
      modoEdicao = false;
      idEmEdicao = null;

      document.getElementById('formTitulo').textContent = 'Cadastro de Produtos';
      document.getElementById('formDescricao').textContent = 'Preencha os dados abaixo para cadastrar um novo produto.';

      document.getElementById('nome').value = '';
      document.getElementById('id').value = '';
      document.getElementById('id').disabled = false;
      document.getElementById('valor').value = '';
      document.getElementById('estoque').value = '';

      document.getElementById('submitBtn').textContent = 'Enviar';
      document.getElementById('btnCancelar').style.display = 'none';
    }

    // ── Adiciona produto na lista ──
    function adicionarProdutoNaLista(produto) {
      document.getElementById('lista-vazia').style.display = 'none';
      const container = document.getElementById('produtos-container');

      const item = document.createElement('div');
      item.className = 'produto-item';
      item.id = `produto-${produto.id}`;

      item.innerHTML = gerarHTMLItem(produto);
      container.appendChild(item);
    }

    // ── Atualiza card existente ──
    function atualizarCardNaLista(produto) {
      const item = document.getElementById(`produto-${produto.id}`);
      if (!item) return;
      const wasOpen = item.classList.contains('open');
      item.innerHTML = gerarHTMLItem(produto);
      if (wasOpen) item.classList.add('open');
    }

    // ── Gera o HTML do card de produto ──
    function gerarHTMLItem(produto) {
      return `
        <div class="produto-header">
          <div class="produto-header-click" onclick="toggleProduto('${produto.id}')">
            <span class="badge-id"># ${produto.id}</span>
            <span class="produto-nome-header" id="nome-display-${produto.id}">${produto.nome}</span>
            <span class="chevron">&#9660;</span>
          </div>
          <button class="btn-editar" onclick="editarProduto('${produto.id}')">Editar</button>
          <button class="btn-excluir" onclick="excluirProduto('${produto.id}')">Excluir</button>
        </div>
        <div class="produto-details" id="details-${produto.id}">
          <table>
            <tr><td>Nome</td><td id="td-nome-${produto.id}">${produto.nome}</td></tr>
            <tr><td>ID</td><td>${produto.id}</td></tr>
            <tr><td>Valor</td><td id="td-valor-${produto.id}">R$ ${produto.valor.toFixed(2)}</td></tr>
            <tr><td>Estoque</td><td id="td-estoque-${produto.id}">${produto.estoque} un.</td></tr>
          </table>
        </div>
      `;
    }

    function excluirProduto(id) {
      var produto = null;
      for (var i = 0; i < produtos.length; i++) {
        if (produtos[i].id === id) { produto = produtos[i]; break; }
      }
      if (!produto) return;

      var confirmar = confirm('Deseja realmente excluir o produto "' + produto.nome + '" (ID: ' + id + ')?');
      if (!confirmar) return;

      // Remove do array de produtos
      for (var j = 0; j < produtos.length; j++) {
        if (produtos[j].id === id) { produtos.splice(j, 1); break; }
      }

      // Remove do array de IDs cadastrados
      var idxCad = idsCadastrados.indexOf(id);
      if (idxCad !== -1) idsCadastrados.splice(idxCad, 1);

      // Remove o card do DOM
      var card = document.getElementById('produto-' + id);
      if (card && card.parentNode) {
        card.parentNode.removeChild(card);
      }

      // Mostra aviso de lista vazia se necessário
      if (produtos.length === 0) {
        document.getElementById('lista-vazia').style.display = '';
      }
    }

    function pesquisar() {
      var termo = document.getElementById('campoPesquisa').value.toLowerCase().trim();
      var cards = document.querySelectorAll('.produto-item');
      var visiveis = 0;
      for (var i = 0; i < cards.length; i++) {
        var card = cards[i];
        var idProd = card.id.replace('produto-', '');
        var nomeProd = card.querySelector('.produto-nome-header').textContent.toLowerCase();
        if (idProd.indexOf(termo) !== -1 || nomeProd.indexOf(termo) !== -1) {
          card.style.display = '';
          visiveis++;
        } else {
          card.style.display = 'none';
        }
      }
      document.getElementById('lista-vazia').style.display =
        (visiveis === 0 && produtos.length > 0) ? '' : (produtos.length === 0 ? '' : 'none');
    }

    function toggleProduto(id) {
      const item = document.getElementById(`produto-${id}`);
      item.classList.toggle('open');
    }
  </script>
</body>

</html>-
"""

# Gera a URL para o Selenium acessar
DEMO_URL = "data:text/html;charset=utf-8," + quote(HTML_DEMO)
print("Página HTML preparada com sucesso.")

from IPython.display import display, HTML
display(HTML(HTML_DEMO))

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

driver = gs.Chrome()

driver.get(DEMO_URL)
print("Título da página:", driver.title)

from IPython.display import display, Markdown

display(Markdown("""
## Fluxo do Teste

1. Abrir a página
2. Preencher nome
3. Preencher id
4. Preencher valor
5. preencher estoque
6. Clicar no botão
7. Validar mensagem de sucesso
"""))

# Configura o tempo de espera e carrega a página
wait = WebDriverWait(driver, 10)
driver.get(DEMO_URL)

# Localiza os elementos da tela
campo_nome = wait.until(EC.presence_of_element_located((By.ID, "nome")))
campo_id = driver.find_element(By.ID, "id")
campo_valor = driver.find_element(By.ID, "valor")
campo_estoque = driver.find_element(By.ID, "estoque")
botao_enviar = driver.find_element(By.ID, "submitBtn")

# Preenche o formulário com dados válidos
campo_nome.clear()
campo_nome.send_keys("Areia pa kh")

campo_id.clear()
campo_id.send_keys("7")

campo_valor.clear()
campo_valor.send_keys("19.90")

campo_estoque.clear()
campo_estoque.send_keys("500")

# Executa a ação e espera o feedback visual
botao_enviar.click()

mensagem_elemento = wait.until(
    EC.visibility_of_element_located((By.ID, "resultMsg"))
)

# Valida se o resultado foi o esperado (Assertion)
mensagem = mensagem_elemento.text
print("Mensagem retornada:", mensagem)

assert "Sucesso" in mensagem
assert "Areia pa kh" in mensagem

print("Teste positivo executado com sucesso.")

wait = WebDriverWait(driver, 10)
driver.get(DEMO_URL)

# Localiza e preenche os campos com novos dados
campo_nome = wait.until(EC.presence_of_element_located((By.ID, "nome")))
campo_id = driver.find_element(By.ID, "id")
campo_valor = driver.find_element(By.ID, "valor")
campo_estoque = driver.find_element(By.ID, "estoque")
botao_enviar = driver.find_element(By.ID, "submitBtn")

campo_nome.clear()
campo_nome.send_keys("Comidinha Nutritiva")

campo_id.clear()
campo_id.send_keys("12")

campo_valor.clear()
campo_valor.send_keys("07.90")

campo_estoque.clear()
campo_estoque.send_keys("1000")

# Envia o formulário
botao_enviar.click()

# Aguarda e valida a mensagem de sucesso
mensagem_elemento = wait.until(
    EC.visibility_of_element_located((By.ID, "resultMsg"))
)

mensagem = mensagem_elemento.text
print("Mensagem retornada:", mensagem)

assert "Sucesso" in mensagem
assert "Comidinha Nutritiva" in mensagem

print("Teste positivo executado com sucesso.")

display(HTML("""
<div style="padding:15px; background-color:#d4edda; color:#155724; border-radius:5px;">
✔ Cadastro realizado com sucesso!
</div>
"""))

wait = WebDriverWait(driver, 10)
driver.get(DEMO_URL)

# Primeiro cadastro para garantir que o ID exista
campo_nome = wait.until(EC.presence_of_element_located((By.ID, "nome")))
campo_id = driver.find_element(By.ID, "id")
campo_valor = driver.find_element(By.ID, "valor")
campo_estoque = driver.find_element(By.ID, "estoque")
botao_enviar = driver.find_element(By.ID, "submitBtn")

campo_nome.clear()
campo_nome.send_keys("Comidinha Nutritiva")

campo_id.clear()
campo_id.send_keys("12")

campo_valor.clear()
campo_valor.send_keys("07.90")

campo_estoque.clear()
campo_estoque.send_keys("1000")

botao_enviar.click()

mensagem_elemento = wait.until(
    EC.visibility_of_element_located((By.ID, "resultMsg"))
)

campo_nome.clear()
campo_nome.send_keys("Comidinha Nutritiva")

campo_id.clear()
campo_id.send_keys("12")

campo_valor.clear()
campo_valor.send_keys("07.90")

campo_estoque.clear()
campo_estoque.send_keys("1000")

botao_enviar.click()

# Valida se o sistema barrou o ID duplicado
mensagem_elemento = wait.until(
    EC.visibility_of_element_located((By.ID, "resultMsg"))
)

mensagem = mensagem_elemento.text
print("Mensagem retornada:", mensagem)

assert "Erro" in mensagem
assert "12" in mensagem

print("Teste negativo executado com sucesso.")

display(HTML("""
<div style="padding:15px; background-color:#f8d7da; color:#721c24; border-radius:5px;">
✖ Erro: campo obrigatório não preenchido
</div>
"""))

"""Fluxo de Teste — Pesquisa

Abrir a página  
Cadastrar produto A  
Cadastrar produto B  
Preencher campo de pesquisa  
Digitar nome do produto desejado  
Visualizar lista filtrada  
Validar que apenas o produto correspondente está visível  
"""

!pip install -q selenium

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
import time

def novo_driver():
    options = Options()
    options.add_argument("--headless=new")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    return webdriver.Chrome(options=options)

driver = novo_driver()
driver.get(DEMO_URL)
time.sleep(1)

driver.find_element(By.ID, "nome").send_keys("Produto A")
driver.find_element(By.ID, "id").send_keys("111")
driver.find_element(By.ID, "valor").send_keys("10")
driver.find_element(By.ID, "estoque").send_keys("5")
driver.find_element(By.ID, "submitBtn").click()
time.sleep(1)

driver.find_element(By.ID, "nome").send_keys("Produto B")
driver.find_element(By.ID, "id").send_keys("222")
driver.find_element(By.ID, "valor").send_keys("20")
driver.find_element(By.ID, "estoque").send_keys("8")
driver.find_element(By.ID, "submitBtn").click()
time.sleep(1)

pesquisa = driver.find_element(By.ID, "campoPesquisa")
pesquisa.send_keys("Produto B")
time.sleep(1)

cards = driver.find_elements(By.CSS_SELECTOR, ".produto-item")
visiveis = [card for card in cards if card.is_displayed()]

assert len(visiveis) == 1
assert "Produto B" in visiveis[0].text

print("Pesquisa Realizada")
driver.quit()

"""Fluxo de Teste — Edição

Abrir a página  
Preencher nome  
Preencher id  
Preencher valor  
Preencher estoque  
Clicar no botão Enviar  
Clicar no botão Editar  
Alterar nome  
Alterar valor  
Alterar estoque  
Clicar no botão Salvar  
Confirmar edição  
Validar mensagem de sucesso  
Validar atualização dos dados na lista  
"""

driver = novo_driver()
driver.get(DEMO_URL)
time.sleep(1)

driver.find_element(By.ID, "nome").send_keys("Produto Teste")
driver.find_element(By.ID, "id").send_keys("123")
driver.find_element(By.ID, "valor").send_keys("50")
driver.find_element(By.ID, "estoque").send_keys("10")
driver.find_element(By.ID, "submitBtn").click()
time.sleep(1)

driver.find_element(By.CLASS_NAME, "btn-editar").click()
time.sleep(1)

nome = driver.find_element(By.ID, "nome")
nome.clear()
nome.send_keys("Produto Editado")

valor = driver.find_element(By.ID, "valor")
valor.clear()
valor.send_keys("99")

estoque = driver.find_element(By.ID, "estoque")
estoque.clear()
estoque.send_keys("15")

driver.find_element(By.ID, "submitBtn").click()
time.sleep(1)

alert = driver.switch_to.alert
alert.accept()
time.sleep(1)

msg = driver.find_element(By.ID, "resultMsg").text
nome_display = driver.find_element(By.ID, "nome-display-123").text

assert "atualizado com sucesso" in msg
assert nome_display == "Produto Editado"

print("Edição de Produtos Retornado")
driver.quit()

"""Fluxo de Teste — Exclusão

Abrir a página  
Preencher nome  
Preencher id  
Preencher valor  
Preencher estoque  
Clicar no botão Enviar  
Localizar produto na lista  
Clicar no botão Excluir  
Confirmar exclusão  
Validar que o produto foi removido  
Validar mensagem de lista vazia (se aplicável)  
"""

driver = novo_driver()
driver.get(DEMO_URL)
time.sleep(1)

driver.find_element(By.ID, "nome").send_keys("Produto Teste")
driver.find_element(By.ID, "id").send_keys("123")
driver.find_element(By.ID, "valor").send_keys("50")
driver.find_element(By.ID, "estoque").send_keys("10")
driver.find_element(By.ID, "submitBtn").click()
time.sleep(1)

driver.find_element(By.CLASS_NAME, "btn-excluir").click()
time.sleep(1)

alert = driver.switch_to.alert
alert.accept()
time.sleep(1)

cards = driver.find_elements(By.CSS_SELECTOR, ".produto-item")
lista_vazia = driver.find_element(By.ID, "lista-vazia")

assert len(cards) == 0
assert lista_vazia.is_displayed()

print("Exclusão Feita com Sucesso")
driver.quit()

driver = novo_driver()
driver.get(DEMO_URL)
time.sleep(1)

driver.find_element(By.ID, "nome").send_keys("Produto Teste")
driver.find_element(By.ID, "id").send_keys("123")
driver.find_element(By.ID, "valor").send_keys("50")
driver.find_element(By.ID, "estoque").send_keys("10")
driver.find_element(By.ID, "submitBtn").click()
time.sleep(1)

pesquisa = driver.find_element(By.ID, "campoPesquisa")
pesquisa.send_keys("50,00")
time.sleep(1)

cards = driver.find_elements(By.CSS_SELECTOR, ".produto-item")
visiveis = [card for card in cards if card.is_displayed()]

assert len(visiveis) == 0

print("Erro validado: pesquisa por valor não retorna resultados")

driver.quit()

# ── Teste 1: Campo vazio ──

# Reinicia o driver caso a sessão tenha expirado
driver.get(DEMO_URL)

wait = WebDriverWait(driver, 10)

campo_nome   = wait.until(EC.presence_of_element_located((By.ID, "nome")))
botao_enviar = driver.find_element(By.ID, "submitBtn")

# Envia o formulário sem preencher nenhum campo
campo_nome.clear()
botao_enviar.click()

mensagem_elemento = wait.until(EC.visibility_of_element_located((By.ID, "resultMsg")))
mensagem = mensagem_elemento.text
print("Mensagem retornada:", mensagem)

assert "Erro" in mensagem
print("Teste campo vazio executado com sucesso.")

display(HTML("""
<div style="padding:15px; background-color:#f8d7da; color:#721c24; border-radius:5px;">
✖ Erro esperado: campo obrigatório não preenchido
</div>
"""))

# ── Teste 3: Valor inválido (negativo) ──
driver.get(DEMO_URL)

wait = WebDriverWait(driver, 10)

campo_nome    = wait.until(EC.presence_of_element_located((By.ID, "nome")))
campo_id      = driver.find_element(By.ID, "id")
campo_valor   = driver.find_element(By.ID, "valor")
campo_estoque = driver.find_element(By.ID, "estoque")
botao_enviar  = driver.find_element(By.ID, "submitBtn")

campo_nome.send_keys("Produto Negativo")
campo_id.send_keys("88")
campo_valor.send_keys("-50")   # valor inválido
campo_estoque.send_keys("10")
botao_enviar.click()

mensagem_elemento = wait.until(EC.visibility_of_element_located((By.ID, "resultMsg")))
mensagem = mensagem_elemento.text
print("Mensagem retornada:", mensagem)

assert "Erro" in mensagem
print("Teste valor inválido executado com sucesso.")

display(HTML("""
<div style="padding:15px; background-color:#f8d7da; color:#721c24; border-radius:5px;">
✖ Erro esperado: valor de venda negativo não permitido
</div>
"""))

# ── Teste 4: Dados incompletos (sem estoque) ──
driver.get(DEMO_URL)

wait = WebDriverWait(driver, 10)

campo_nome   = wait.until(EC.presence_of_element_located((By.ID, "nome")))
campo_id     = driver.find_element(By.ID, "id")
campo_valor  = driver.find_element(By.ID, "valor")
botao_enviar = driver.find_element(By.ID, "submitBtn")

campo_nome.send_keys("Produto Incompleto")
campo_id.send_keys("77")
campo_valor.send_keys("25.00")
# campo estoque deixado vazio propositalmente
botao_enviar.click()

mensagem_elemento = wait.until(EC.visibility_of_element_located((By.ID, "resultMsg")))
mensagem = mensagem_elemento.text
print("Mensagem retornada:", mensagem)

assert "Erro" in mensagem
print("Teste dados incompletos executado com sucesso.")

display(HTML("""
<div style="padding:15px; background-color:#f8d7da; color:#721c24; border-radius:5px;">
✖ Erro esperado: dados incompletos - campo estoque não preenchido
</div>
"""))

# ── PASSO 7 – Testes de API (aplicado nas entradas do sistema) ──
# Como o projeto não possui API, os testes validam
# status (sucesso/erro) e resposta (mensagem retornada) do formulário.

# ── Teste válido 1: Cadastro com dados corretos ──
driver.get(DEMO_URL)

wait = WebDriverWait(driver, 10)

campo_nome    = wait.until(EC.presence_of_element_located((By.ID, "nome")))
campo_id      = driver.find_element(By.ID, "id")
campo_valor   = driver.find_element(By.ID, "valor")
campo_estoque = driver.find_element(By.ID, "estoque")
botao_enviar  = driver.find_element(By.ID, "submitBtn")

campo_nome.send_keys("Produto Válido")
campo_id.send_keys("10")
campo_valor.send_keys("50.00")
campo_estoque.send_keys("100")
botao_enviar.click()

mensagem_elemento = wait.until(EC.visibility_of_element_located((By.ID, "resultMsg")))
mensagem = mensagem_elemento.text
print("Status:", "Sucesso" if "Sucesso" in mensagem else "Erro")
print("Resposta:", mensagem)

assert "Sucesso" in mensagem
print("Teste válido 1 passou.")

display(HTML("""
<div style="padding:15px; background-color:#d4edda; color:#155724; border-radius:5px;">
✔ Status: 200 OK – Cadastro realizado com sucesso
</div>
"""))

# ── Teste válido 2: Cadastro com estoque zero (permitido) ──
driver.get(DEMO_URL)

wait = WebDriverWait(driver, 10)

campo_nome    = wait.until(EC.presence_of_element_located((By.ID, "nome")))
campo_id      = driver.find_element(By.ID, "id")
campo_valor   = driver.find_element(By.ID, "valor")
campo_estoque = driver.find_element(By.ID, "estoque")
botao_enviar  = driver.find_element(By.ID, "submitBtn")

campo_nome.send_keys("Produto Sem Estoque")
campo_id.send_keys("20")
campo_valor.send_keys("15.00")
campo_estoque.send_keys("0")   # estoque zero é permitido
botao_enviar.click()

mensagem_elemento = wait.until(EC.visibility_of_element_located((By.ID, "resultMsg")))
mensagem = mensagem_elemento.text
print("Status:", "Sucesso" if "Sucesso" in mensagem else "Erro")
print("Resposta:", mensagem)

assert "Sucesso" in mensagem
print("Teste válido 2 passou.")

display(HTML("""
<div style="padding:15px; background-color:#d4edda; color:#155724; border-radius:5px;">
✔ Status: 200 OK – Cadastro com estoque zero aceito corretamente
</div>
"""))

# ── Teste inválido 1: ID duplicado ──
driver.get(DEMO_URL)

wait = WebDriverWait(driver, 10)

campo_nome    = wait.until(EC.presence_of_element_located((By.ID, "nome")))
campo_id      = driver.find_element(By.ID, "id")
campo_valor   = driver.find_element(By.ID, "valor")
campo_estoque = driver.find_element(By.ID, "estoque")
botao_enviar  = driver.find_element(By.ID, "submitBtn")

# Primeiro cadastro
campo_nome.send_keys("Produto Original")
campo_id.send_keys("10")
campo_valor.send_keys("30.00")
campo_estoque.send_keys("50")
botao_enviar.click()

wait.until(EC.visibility_of_element_located((By.ID, "resultMsg")))

# Segundo cadastro com mesmo ID
campo_nome    = driver.find_element(By.ID, "nome")
campo_id      = driver.find_element(By.ID, "id")
campo_valor   = driver.find_element(By.ID, "valor")
campo_estoque = driver.find_element(By.ID, "estoque")

campo_nome.send_keys("Produto Duplicado")
campo_id.send_keys("10")   # ID já cadastrado
campo_valor.send_keys("30.00")
campo_estoque.send_keys("50")
botao_enviar.click()

mensagem_elemento = wait.until(EC.visibility_of_element_located((By.ID, "resultMsg")))
mensagem = mensagem_elemento.text
print("Status:", "Erro" if "Erro" in mensagem else "Sucesso")
print("Resposta:", mensagem)

assert "Erro" in mensagem
assert "10" in mensagem
print("Teste inválido 1 passou.")

display(HTML("""
<div style="padding:15px; background-color:#f8d7da; color:#721c24; border-radius:5px;">
✖ Status: 400 Bad Request – ID duplicado rejeitado corretamente
</div>
"""))

# ── Teste inválido 2: Estoque negativo ──
driver.get(DEMO_URL)

wait = WebDriverWait(driver, 10)

campo_nome    = wait.until(EC.presence_of_element_located((By.ID, "nome")))
campo_id      = driver.find_element(By.ID, "id")
campo_valor   = driver.find_element(By.ID, "valor")
campo_estoque = driver.find_element(By.ID, "estoque")
botao_enviar  = driver.find_element(By.ID, "submitBtn")

campo_nome.send_keys("Produto Inválido")
campo_id.send_keys("30")
campo_valor.send_keys("10.00")
campo_estoque.send_keys("-5")   # estoque negativo
botao_enviar.click()

mensagem_elemento = wait.until(EC.visibility_of_element_located((By.ID, "resultMsg")))
mensagem = mensagem_elemento.text
print("Status:", "Erro" if "Erro" in mensagem else "Sucesso")
print("Resposta:", mensagem)

assert "Erro" in mensagem
print("Teste inválido 2 passou.")

display(HTML("""
<div style="padding:15px; background-color:#f8d7da; color:#721c24; border-radius:5px;">
✖ Status: 400 Bad Request – Estoque negativo rejeitado corretamente
</div>
"""))